### ISSUE TITLE
ETP-879:The modulescript MultipleMappingsMigration.java from the module com.etendoerp.etendorx fails while compiling for oracle database

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/com.etendoerp.platform.extensions#28]
**Error's description**
The modulescript MultipleMappingsMigration.java class in the com.etendoerp.etendorx module fails to compile when running on an Oracle database.

**Steps to reproduce the error**

1. Install the com.etendoerp.etendorx module by adding the below in build.gradle:
**implementation ('com.etendoerp:platform.extensions:latest.release')**
2. Ensure the database is set up with Oracle.
3. Run the command: **./gradlew update.database** which will execute the MultipleMappingsMigration.java modulescript.
4. Observe the failure during the compilation as below:
**[ant:java] Execution of moduleScript com.etendoerp.etendorx.modulescript.MultipleMappingsMigration failed.
[ant:java]      at org.openbravo.modulescript.ModuleScriptHandler.execute(ModuleScriptHandler.java:98)
[ant:java]      at org.openbravo.ddlutils.process.DBUpdater.executeModuleScripts(DBUpdater.java:177)
[ant:java]      at org.openbravo.ddlutils.process.DBUpdater.update(DBUpdater.java:119)
[ant:java]      at org.openbravo.ddlutils.task.AlterDatabaseDataAll.doExecute(AlterDatabaseDataAll.java:69)
[ant:java]      at org.openbravo.ddlutils.task.BaseDatabaseTask.execute(BaseDatabaseTask.java:81)
[ant:java]      at org.openbravo.ddlutils.task.AlterDatabaseJava.main(AlterDatabaseJava.java:71)
[ant:java] Exception in thread "main" Execution of moduleScript com.etendoerp.etendorx.modulescript.MultipleMappingsMigration failed.
[ant:java]      at org.openbravo.ddlutils.process.DBUpdater.update(DBUpdater.java:146)
[ant:java]      at org.openbravo.ddlutils.task.AlterDatabaseDataAll.doExecute(AlterDatabaseDataAll.java:69)
[ant:java]      at org.openbravo.ddlutils.task.BaseDatabaseTask.execute(BaseDatabaseTask.java:81)
[ant:java]      at org.openbravo.ddlutils.task.AlterDatabaseJava.main(AlterDatabaseJava.java:71)
[ant:java] Caused by: Execution of moduleScript com.etendoerp.etendorx.modulescript.MultipleMappingsMigration failed.
[ant:java]      at org.openbravo.modulescript.ModuleScriptHandler.execute(ModuleScriptHandler.java:98)
[ant:java]      at org.openbravo.ddlutils.process.DBUpdater.executeModuleScripts(DBUpdater.java:177)
[ant:java]      at org.openbravo.ddlutils.process.DBUpdater.update(DBUpdater.java:119)
[ant:java]      ... 3 more**
![Screenshot from 2024-12-12 14-33-17](https://github.com/user-attachments/assets/957d9e7c-b7ea-42ca-9e2b-401c83c026c6)

**Required Configurations (if necessary)**

**Expected behavior**

The MultipleMappingsMigration.java modulescript should compile and execute successfully without errors in an Oracle database environment.

**Affected Version** 

¿ Latest/Specific ? **Latest**

Version number: Core-24.2.8

**Solution Design (optional)**

Other test cases

  Given:
  When:
  Then:

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [2.8.0](https://github.com/etendosoftware/com.etendoerp.platform.extensions/releases/tag/2.8.0) ⚡ 🚀
